### ISSUE TITLE
Adaptive Cards

### ISSUE THREAD

**Issue by chrishentges** [alexkargin/msteams-bot-php#1]
Hello,

Thank you for the package.  Are you able to provide an example for making a simple adaptive card?  For some reason, I'm having issues creating one.  Below is an example of what I'm trying to make.

`{
    "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "This is some **bold** text"
        },
        {
            "type": "TextBlock",
            "text": "This is some _italic_ text"
        },
        {
            "type": "TextBlock",
            "text": "- Bullet \r- List \r",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "1. Numbered\r2. List\r",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "Check out [Adaptive Cards](https://adaptivecards.io)"
        }
    ]
}`

**Comment by alexkargin** [comment]
Hello,
For example, you can send an adaptive card in response to the "test" message using the following code

```
$bot = new TeamsBot\BotListener($bot_id, $bot_secret);
// Handled when user sends 'test' to bot
$bot->onText('test', static  function (Bot $bot) {
    // create Activity
    $message = $bot->createMessage();
    // add Adaptive Card
    $att = new TeamsBot\Card\AdaptiveCard();
    $att->setContentFromJson('
{ "$schema": "https://adaptivecards.io/schemas/adaptive-card.json", "type": "AdaptiveCard", "version": "1.0", "body": [ { "type": "TextBlock", "text": "This is some **bold** text" }, { "type": "TextBlock", "text": "This is some _italic_ text" }, { "type": "TextBlock", "text": "- Bullet \r- List \r", "wrap": true }, { "type": "TextBlock", "text": "1. Numbered\r2. List\r", "wrap": true }, { "type": "TextBlock", "text": "Check out [Adaptive Cards](https://adaptivecards.io)" } ] }
    ');
    $message->addAttachment($att);
    // send new message
    $bot->postMessage($message);
});
```

The result is
![HideFrame_Снимок экрана 2021-08-31 141006](https://user-images.githubusercontent.com/62253635/131493232-ff0913a2-a2f3-4a9b-9eb1-3ba37bc4e0c7.png)

**Comment by chrishentges** [comment]
Works great!  Thank you
